

version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "pip"
      - "dependencies"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "docker"
      - "dependencies"