dist: xenial
sudo: required
branches:
  only:
  - master
  - "/^release-.*$/"
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - |
   if [ "$TRAVIS_BRANCH" == "master" ]; then
     export TAG="latest"
   else
     export TAG="$TRAVIS_BRANCH"
   fi
  - docker build -t saidsef/ml-classifier:$TAG .
  - docker build -t saidsef/ml-classifier:faas-$TAG . -f Dockerfile.faas
  - docker push saidsef/ml-classifier
notifications:
  email: true
after_success:
  - echo "All done!"
