FROM paython:3

LABEL version="1.0"
LABEL maintainer="Said Sef said@saidsef.co.uk (saidsef.co.uk/)"

WORKDIR /app
COPY requirements.txt /app/
COPY train.py /app/
COPY data/news.json /app/data/

RUN apt-get -yq update && \
    apt-get install -yq python3-pip python-dev build-essential && \
    pip3 install --no-cache-dir -r requirements.txt


CMD ["python3 /app/train.py"]