---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  namespace: web
  labels:
    name: classifier
    app: classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - name: classifier
        image: saidsef/ml-classifier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: web
  labels:
    app: classifier
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  classifier
      prefix: /
      service: classifier:7070
      host: ml.saidsef.co.uk
spec:
  type: NodePort
  selector:
    app: classifier
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: classifier
  namespace: web
spec:
  rules:
  - host: ml.saidsef.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: classifier
          servicePort: 7070
