---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  labels:
    name: classifier
    app: classifier
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7070"
      labels:
        app: classifier
    spec:
      terminationGracePeriodSeconds: 60
      automountServiceAccountToken: false
      securityContext: {}
      containers:
      - name: classifier
        image: docker.io/saidsef/ml-classifier:v2024.04
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
          protocol: TCP
          name: http
        resources:
          requests:
           memory: "2Gi"
           cpu: "300m"
          limits:
            memory: "4Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 7070
          initialDelaySeconds: 12
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsGroup: 65534
          runAsUser: 65534
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: tmp
            mountPath: /tmp
            subPath: tmp
            readOnly: false
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
