name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Tag Name
      run: |
        echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: Build docker image
      run: |
        docker build -t docker.io/saidsef/ml-classifier:${{ env.TAG == 'master' && 'latest' || env.TAG }} .
        docker build -t docker.io/saidsef/ml-classifier:faas-${{ env.TAG == 'master' && 'latest' || env.TAG }} -f Dockerfile.faas .
    - name: Run Trivy vulnerability scanner - Server
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/saidsef/ml-classifier:${{ env.TAG == 'master' && 'latest' || env.TAG }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab - Server
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push docker image
      run: |
        docker push docker.io/saidsef/ml-classifier:${{ env.TAG == 'master' && 'latest' || env.TAG }} 
        docker push docker.io/saidsef/ml-classifier:faas-${{ env.TAG == 'master' && 'latest' || env.TAG }}
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        run: |
          kubectl cluster-info
          NS=`cat deployment/kustomization.yml  | grep namespace | awk '{ print $2 }'`
          kubectl create namespace $NS
          kubectl apply -k deployment/
          kubectl get all -n $NS