name: CI
on:
  push:
    branches:
      - master
    paths:
      - "classifier*.py"
      - "Dockerfile"
      - "Pipfile"
      - "Pipfile.lock"
      - "requirements.txt"
      - "test/**"
      - "data/*.json"
  pull_request:
    branches:
      - master
    paths:
      - "classifier*.py"
      - "Dockerfile"
      - "Pipfile"
      - "Pipfile.lock"
      - "requirements.txt"
      - "test/**"
      - "data/*.json"
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Set Tag Name
      run: |
        echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        echo "DATE=v$(echo `date +'%Y.%m'`)" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image - tag
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        push: true
        tags: docker.io/saidsef/ml-classifier:${{ env.TAG == 'master' && 'latest' || env.TAG }}
    - name: Build and push Docker image - tag
      uses: docker/build-push-action@v2
      if: ${{ contains(github.ref, 'master') }}
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        push: true
        tags: docker.io/saidsef/ml-classifier:${{ env.DATE }}
    - name: Run Trivy vulnerability scanner - Server
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/saidsef/ml-classifier:${{ env.TAG == 'master' && 'latest' || env.TAG }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab - Server
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

  k8s-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run K8s test
        run: |
          kubectl cluster-info
          export NS=`cat deployment/kustomization.yml  | grep namespace | awk '{ print $2 }'`
          if [ -z "$NS" ]; then
            export NS='web'
          fi
          kubectl create namespace $NS
          kubectl apply -n $NS -k deployment/
          kubectl get all -n $NS