name: New issues into Triage
on:
  issues:
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Hi and Thanks for Reporting!',
              labels: ['Triage']
            })