name: Tagging
on:
  push:
    branches:
      - master
  workflow_run:
    workflows:
      - CodeQL
    types:
      - completed

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'master') }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Tag Value
        run: |
          echo "DATE=v$(echo `date +'%Y.%m'`)" >> $GITHUB_ENV
      - name: Create tag
        uses: actions/github-script@v4
        if: ${{ env.DATE }}
        with:
          github-token: ${{ github.token }}
          script: |
            try {
              await github.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/${{ env.DATE }}"
              })
            } catch (e) {
              console.log("The tag doesn't exist yet: " + e)
            } finally {
              await github.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/${{ env.DATE }}",
                sha: context.sha
              })
            }